In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

In [2]:
cities = pd.read_csv('uscities.csv')
cities.head

<bound method NDFrame.head of                city    city_ascii state_id    state_name  county_fips  \
0       South Creek   South Creek       WA    Washington        53053
1            Roslyn        Roslyn       WA    Washington        53037
2           Sprague       Sprague       WA    Washington        53043
3        Gig Harbor    Gig Harbor       WA    Washington        53053
4      Lake Cassidy  Lake Cassidy       WA    Washington        53061
...             ...           ...      ...           ...          ...
28884      Montrose      Montrose       SD  South Dakota        46087
28885     Spearfish     Spearfish       SD  South Dakota        46081
28886         Emery         Emery       SD  South Dakota        46061
28887     Watertown     Watertown       SD  South Dakota        46029
28888       Buffalo       Buffalo       SD  South Dakota        46063

      county_name county_fips_all county_name_all      lat       lng  \
0          Pierce           53053          Pierce  46.9994 -122.3921
1        Kittitas           53037        Kittitas  47.2507 -121.0989
2         Lincoln           53043         Lincoln  47.3048 -117.9713
3          Pierce           53053          Pierce  47.3352 -122.5968
4       Snohomish           53061       Snohomish  48.0639 -122.0920
...           ...             ...             ...      ...       ...
28884      McCook           46087          McCook  43.7002  -97.1843
28885    Lawrence           46081        Lawrence  44.4912 -103.8167
28886      Hanson           46061          Hanson  43.6020  -97.6195
28887   Codington           46029       Codington  44.9094  -97.1532
28888     Harding           46063         Harding  45.5864 -103.5434

       population  density   source  military  incorporated  \
0          2500.0    125.0  polygon     False          True
1           947.0     84.0  polygon     False          True
2           441.0    163.0  polygon     False          True
3          9507.0    622.0  polygon     False          True
4          3591.0    131.0  polygon     False          True
...           ...      ...      ...       ...           ...
28884       442.0    414.0  polygon     False          True
28885     12675.0    272.0  polygon     False          True
28886       455.0    384.0  polygon     False          True
28887     21837.0    475.0  polygon     False          True
28888       346.0    241.0  polygon     False          True

                  timezone  ranking               zips          id
0      America/Los_Angeles        3  98580 98387 98338  1840042075
1      America/Los_Angeles        3  98941 98068 98925  1840019842
2      America/Los_Angeles        3              99032  1840021107
3      America/Los_Angeles        3        98332 98335  1840019855
4      America/Los_Angeles        3  98223 98258 98270  1840041959
...                    ...      ...                ...         ...
28884      America/Chicago        3              57048  1840002659
28885       America/Denver        3        57783 57799  1840002374
28886      America/Chicago        3              57332  1840002644
28887      America/Chicago        3              57201  1840002156
28888       America/Denver        3              57720  1840002018

[28889 rows x 19 columns]>

In [4]:
cities = cities.loc[~cities["population"].isnull()]

In [5]:
cities = cities.sort_values("population", ascending=False)

In [6]:
cities = cities.head(500)
cities

,city,city_ascii,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
9730,New York,New York,NY,New York,36061,New York,36061,New York,40.6943,-73.9249,19354922.0,11083.0,polygon,False,True,America/New_York,1,11229 11226 11225 11224 11222 11221 11220 1138...,1840034016
14121,Los Angeles,Los Angeles,CA,California,6037,Los Angeles,06037,Los Angeles,34.1139,-118.4068,12815475.0,3295.0,polygon,False,True,America/Los_Angeles,1,90291 90293 90292 91316 91311 90037 90031 9000...,1840020491
16289,Chicago,Chicago,IL,Illinois,17031,Cook,17031,Cook,41.8373,-87.6862,8675982.0,4612.0,polygon,False,True,America/Chicago,1,60018 60649 60641 60640 60643 60642 60645 6064...,1840000494
2882,Miami,Miami,FL,Florida,12086,Miami-Dade,12086,Miami-Dade,25.7839,-80.2102,6381966.0,4969.0,polygon,False,True,America/New_York,1,33129 33125 33126 33127 33128 33149 33144 3314...,1840015149
4464,Dallas,Dallas,TX,Texas,48113,Dallas,48113|48085|48121|48257|48397,Dallas|Collin|Denton|Kaufman|Rockwall,32.7936,-96.7662,5733259.0,1524.0,polygon,False,True,America/Chicago,1,75287 75098 75233 75254 75251 75252 75253 7503...,1840019440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12717,Lafayette,Lafayette,CO,Colorado,8013,Boulder,08013,Boulder,39.9949,-105.0997,91985.0,1160.0,polygon,False,True,America/Denver,3,80026,1840020180
20925,Edmond,Edmond,OK,Oklahoma,40109,Oklahoma,40109,Oklahoma,35.6689,-97.4159,91950.0,419.0,polygon,False,True,America/Chicago,3,73012 73013 73007 73003 73034,1840020423
18129,Fishers,Fishers,IN,Indiana,18057,Hamilton,18057,Hamilton,39.9589,-85.9665,91832.0,1005.0,polygon,False,True,America/Indiana/Indianapolis,3,46038 46040 46256 46037,1840010496
14320,Westminster,Westminster,CA,California,6059,Orange,06059,Orange,33.7523,-117.9938,91564.0,3520.0,polygon,False,True,America/Los_Angeles,2,92683 92684 92685,1840021969
20582,Germantown,Germantown,MD,Maryland,24031,Montgomery,24031,Montgomery,39.1755,-77.2643,91447.0,2073.0,polygon,False,False,America/New_York,2,20876 20874 20875,1840005840

In [7]:
cities.to_csv('topcities.csv')